import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../styles/custom.css';
import TanstackProvider from '~/providers/TanstackProvider';
import { AuthProvider } from '~/providers/AuthContextProvider';
import StoreProvider from '~/providers/StoreProvider';
import { Toaster } from '~/components/ui/toaster';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Spotify App',
	description: 'Generated by spotify',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={inter.className}>
				<StoreProvider>
					<TanstackProvider>
						<AuthProvider>{children}</AuthProvider>
						<Toaster />
					</TanstackProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
